### ISSUE TITLE
Tests fail during build

### ISSUE THREAD

**Issue by ncafferkey** [angryelectron/thingspeak-java#1]
I tried to build from the sources in the ZIP file, but it failed the tests.

Output from failed tests:

-do-test-run:
    [junit] Testsuite: com.angryelectron.thingspeak.FeedTest
    [junit] log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
    [junit] log4j:WARN Please initialize the log4j system properly.
    [junit] Tests run: 13, Failures: 1, Errors: 6, Time elapsed: 72.738 sec
    [junit] 
    [junit] ------------- Standard Error -----------------
    [junit] log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
    [junit] log4j:WARN Please initialize the log4j system properly.
    [junit] ------------- ---------------- ---------------
    [junit] Testcase: testGetChannelFeedWithOptions(com.angryelectron.thingspeak.FeedTest): Caused an ERROR
    [junit] Entry with ID 168 not found in feed.
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Entry with ID 168 not found in feed.
    [junit]     at com.angryelectron.thingspeak.Feed.getEntry(Feed.java:209)
    [junit]     at com.angryelectron.thingspeak.Feed.getChannelLastEntry(Feed.java:223)
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetChannelFeedWithOptions(FeedTest.java:133)
    [junit] 
    [junit] 
    [junit] Testcase: testGetLastEntryWithTimezoneOffset(com.angryelectron.thingspeak.FeedTest):    FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetLastEntryWithTimezoneOffset(FeedTest.java:182)
    [junit] 
    [junit] 
    [junit] Testcase: testGetFieldFeed(com.angryelectron.thingspeak.FeedTest):  Caused an ERROR
    [junit] Entry with ID 168 not found in feed.
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Entry with ID 168 not found in feed.
    [junit]     at com.angryelectron.thingspeak.Feed.getEntry(Feed.java:209)
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetFieldFeed(FeedTest.java:196)
    [junit] 
    [junit] 
    [junit] Testcase: testGetFieldFeedWithOptions(com.angryelectron.thingspeak.FeedTest):   Caused an ERROR
    [junit] Entry with ID 168 not found in feed.
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Entry with ID 168 not found in feed.
    [junit]     at com.angryelectron.thingspeak.Feed.getEntry(Feed.java:209)
    [junit]     at com.angryelectron.thingspeak.Feed.getChannelLastEntry(Feed.java:223)
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetFieldFeedWithOptions(FeedTest.java:215)
    [junit] 
    [junit] 
    [junit] Testcase: testGetFieldFeedLastEntryWithOptions(com.angryelectron.thingspeak.FeedTest):  Caused an ERROR
    [junit] org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit] com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit]     at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
    [junit]     at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:64)
    [junit]     at com.angryelectron.thingspeak.Channel.thingRequest(Channel.java:124)
    [junit]     at com.angryelectron.thingspeak.Channel.getLastFieldEntry(Channel.java:271)
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetFieldFeedLastEntryWithOptions(FeedTest.java:241)
    [junit] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit]     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:130)
    [junit]     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
    [junit]     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
    [junit]     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
    [junit]     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
    [junit]     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    [junit]     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    [junit]     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    [junit]     at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:126)
    [junit] Caused by: java.net.SocketTimeoutException: connect timed out
    [junit]     at java.net.PlainSocketImpl.socketConnect(Native Method)
    [junit]     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    [junit]     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    [junit]     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    [junit]     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    [junit]     at java.net.Socket.connect(Socket.java:579)
    [junit]     at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
    [junit]     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
    [junit] 
    [junit] 
    [junit] Testcase: testGetStatus(com.angryelectron.thingspeak.FeedTest): Caused an ERROR
    [junit] org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit] com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit]     at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
    [junit]     at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:64)
    [junit]     at com.angryelectron.thingspeak.Channel.thingRequest(Channel.java:102)
    [junit]     at com.angryelectron.thingspeak.Channel.getStatusFeed(Channel.java:283)
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetStatus(FeedTest.java:254)
    [junit] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit]     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:130)
    [junit]     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
    [junit]     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
    [junit]     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
    [junit]     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
    [junit]     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    [junit]     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    [junit]     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    [junit]     at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:126)
    [junit] Caused by: java.net.SocketTimeoutException: connect timed out
    [junit]     at java.net.PlainSocketImpl.socketConnect(Native Method)
    [junit]     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    [junit]     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    [junit]     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    [junit]     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    [junit]     at java.net.Socket.connect(Socket.java:579)
    [junit]     at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
    [junit]     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
    [junit] 
    [junit] 
    [junit] Testcase: testGetStatusWithOptions(com.angryelectron.thingspeak.FeedTest):  Caused an ERROR
    [junit] org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit] com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit]     at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
    [junit]     at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:64)
    [junit]     at com.angryelectron.thingspeak.Channel.thingRequest(Channel.java:124)
    [junit]     at com.angryelectron.thingspeak.Channel.getStatusFeed(Channel.java:297)
    [junit]     at com.angryelectron.thingspeak.FeedTest.testGetStatusWithOptions(FeedTest.java:266)
    [junit] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/184.106.153.149] failed: connect timed out
    [junit]     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:130)
    [junit]     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
    [junit]     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
    [junit]     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
    [junit]     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
    [junit]     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    [junit]     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    [junit]     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    [junit]     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    [junit]     at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:126)
    [junit] Caused by: java.net.SocketTimeoutException: connect timed out
    [junit]     at java.net.PlainSocketImpl.socketConnect(Native Method)
    [junit]     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    [junit]     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    [junit]     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    [junit]     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    [junit]     at java.net.Socket.connect(Socket.java:579)
    [junit]     at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
    [junit]     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
    [junit] 
    [junit] 
    [junit] Test com.angryelectron.thingspeak.FeedTest FAILED
    [junit] Testsuite: com.angryelectron.thingspeak.UpdateTest
    [junit] testUpdatePublicChannelWithInvalidAPIKey
    [junit] log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
    [junit] log4j:WARN Please initialize the log4j system properly.
    [junit] testUpdateSlowerThanAPIRateLimit
    [junit] Waiting for rate limit to expire.
    [junit] testUpdateFasterThanAPIRateLimit
    [junit] testUpdatePublicChannel
    [junit] Tests run: 4, Failures: 0, Errors: 1, Time elapsed: 69.372 sec
    [junit] 
    [junit] ------------- Standard Output ---------------
    [junit] testUpdatePublicChannelWithInvalidAPIKey
    [junit] testUpdateSlowerThanAPIRateLimit
    [junit] Waiting for rate limit to expire.
    [junit] testUpdateFasterThanAPIRateLimit
    [junit] testUpdatePublicChannel
    [junit] ------------- ---------------- ---------------
    [junit] ------------- Standard Error -----------------
    [junit] log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
    [junit] log4j:WARN Please initialize the log4j system properly.
    [junit] ------------- ---------------- ---------------
    [junit] Testcase: testUpdateChannel(com.angryelectron.thingspeak.UpdateTest):   Caused an ERROR
    [junit] Update failed.
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Update failed.
    [junit]     at com.angryelectron.thingspeak.Channel.update(Channel.java:159)
    [junit]     at com.angryelectron.thingspeak.UpdateTest.testUpdateChannel(UpdateTest.java:44)
    [junit] 
    [junit] 
    [junit] Test com.angryelectron.thingspeak.UpdateTest FAILED
    [junit] Testsuite: com.angryelectron.thingspeak.log4j.ThingSpeakAppenderTest
    [junit] append.
    [junit] appendWithServer.
    [junit] Nov 06, 2014 2:16:43 PM com.angryelectron.thingspeak.log4j.ThingSpeakAppender append
    [junit] SEVERE: null
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Update failed.
    [junit]     at com.angryelectron.thingspeak.Channel.update(Channel.java:159)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppender.append(ThingSpeakAppender.java:123)
    [junit]     at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:221)
    [junit]     at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:57)
    [junit]     at org.apache.log4j.Category.callAppenders(Category.java:187)
    [junit]     at org.apache.log4j.Category.forcedLog(Category.java:372)
    [junit]     at org.apache.log4j.Category.log(Category.java:846)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppenderTest.testAppendWithServer(ThingSpeakAppenderTest.java:63)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]     at java.lang.reflect.Method.invoke(Method.java:606)
    [junit]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    [junit]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    [junit]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    [junit]     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    [junit]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit]     at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    [junit]     at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:518)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1052)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:906)
    [junit] 
    [junit] Tests run: 2, Failures: 0, Errors: 0, Time elapsed: 1.692 sec
    [junit] 
    [junit] ------------- Standard Output ---------------
    [junit] append.
    [junit] appendWithServer.
    [junit] ------------- ---------------- ---------------
    [junit] ------------- Standard Error -----------------
    [junit] Nov 06, 2014 2:16:43 PM com.angryelectron.thingspeak.log4j.ThingSpeakAppender append
    [junit] SEVERE: null
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Update failed.
    [junit]     at com.angryelectron.thingspeak.Channel.update(Channel.java:159)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppender.append(ThingSpeakAppender.java:123)
    [junit]     at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:221)
    [junit]     at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:57)
    [junit]     at org.apache.log4j.Category.callAppenders(Category.java:187)
    [junit]     at org.apache.log4j.Category.forcedLog(Category.java:372)
    [junit]     at org.apache.log4j.Category.log(Category.java:846)
    [junit] Nov 06, 2014 2:16:43 PM com.angryelectron.thingspeak.log4j.ThingSpeakAppender append
    [junit] SEVERE: null
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Update failed.
    [junit]     at com.angryelectron.thingspeak.Channel.update(Channel.java:159)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppender.append(ThingSpeakAppender.java:123)
    [junit]     at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:221)
    [junit]     at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:57)
    [junit]     at org.apache.log4j.Category.callAppenders(Category.java:187)
    [junit]     at org.apache.log4j.Category.forcedLog(Category.java:372)
    [junit]     at org.apache.log4j.Category.log(Category.java:846)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppenderTest.testAppendWithServer(ThingSpeakAppenderTest.java:63)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]     at java.lang.reflect.Method.invoke(Method.java:606)
    [junit]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    [junit]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    [junit]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    [junit]     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    [junit]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit]     at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    [junit]     at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:518)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1052)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:906)
    [junit] 
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppenderTest.testAppendWithServer(ThingSpeakAppenderTest.java:63)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]     at java.lang.reflect.Method.invoke(Method.java:606)
    [junit]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    [junit]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    [junit]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    [junit]     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    [junit]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit]     at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    [junit]     at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:518)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1052)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:906)
    [junit] 
    [junit] Nov 06, 2014 2:16:43 PM com.angryelectron.thingspeak.log4j.ThingSpeakAppender append
    [junit] SEVERE: null
    [junit] com.angryelectron.thingspeak.ThingSpeakException: Update failed.
    [junit]     at com.angryelectron.thingspeak.Channel.update(Channel.java:159)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppender.append(ThingSpeakAppender.java:123)
    [junit]     at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:221)
    [junit]     at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:57)
    [junit]     at org.apache.log4j.Category.callAppenders(Category.java:187)
    [junit]     at org.apache.log4j.Category.forcedLog(Category.java:372)
    [junit]     at org.apache.log4j.Category.log(Category.java:846)
    [junit]     at com.angryelectron.thingspeak.log4j.ThingSpeakAppenderTest.testAppendWithServer(ThingSpeakAppenderTest.java:63)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]     at java.lang.reflect.Method.invoke(Method.java:606)
    [junit]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    [junit]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    [junit]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    [junit]     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    [junit]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    [junit]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit]     at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    [junit]     at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:518)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1052)
    [junit]     at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:906)
    [junit] 
    [junit] ------------- ---------------- ---------------

test-report:

-post-test-run:

BUILD FAILED
/home/neil/ThingSpeak/thingspeak-java-master/nbproject/build-impl.xml:1308: Some tests failed; see details above.

Total time: 2 minutes 29 seconds

**Comment by ajeetsachan** [comment]
I am running the test behind proxy, can you please let me know if any changes require to run it successfully, currently facing exception,though VM Arguments (-Djava.net.useSystemProxies=true) are configured.

com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.ConnectTimeoutException: Connect to api.thingspeak.com:80 [api.thingspeak.com/127.0.0.1] failed: Connect timed out
