### ISSUE TITLE
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at character 1

### ISSUE THREAD

**Issue by b-madhukar** [angryelectron/thingspeak-java#8]
package com.angryelectron.thingspeak;

public class ThingExample {

    public static void main(String[] args) throws Exception {
        String apireadKey = "XDIZKEDYZ0KUQ";
        Channel channel = new Channel(5287, apireadKey);        
        try {            
            // write something
       //     Entry writeEntry = new Entry();
           // writeEntry.setField(1, "Hello");            
            // read it back
        	
            Entry readEntry = channel.getLastChannelEntry();
            System.out.println(readEntry.getField(1));
        } catch(Exception ex) {
            System.out.println(ex);
        } 
    }
    
}

**Comment by abythell** [comment]
You're likely making a bad request.  From the looks of it, you are trying to write to a channel using a read-key, if your variables are named appropriately.  Please see the javadocs and use the appropriate constructor:

* Channel(java.lang.Integer channelId)Constructor for a public, read-only, Thingspeak channel.
* Channel(java.lang.Integer channelId, java.lang.String writeKey)Constructor for a public, writeable, Thingspeak channel.
* Channel(java.lang.Integer channelId, java.lang.String writeKey, java.lang.String readKey)Constructor for a private, writeable, Thingspeak channel.

**Comment by b-madhukar** [comment]
Thank you for your quick help

Channel(java.lang.Integer channelId, java.lang.String writeKey, java.lang.String readKey)Constructor for a private, writeable, Thingspeak channel.

Helped me:-)
